### PR TITLE
Bump up Ruby version to 2.5.2

### PR DESCRIPTION
**Pull request by koshigoe**
Blocker
----

- [x] #62

Why
----

- [Ruby 2.5.2 Released](https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-5-2-released/)

How
----

- [x] Update SPEC file

Verify
----

- [x] Install RPMs
   - CentOS 6: https://235-25909051-gh.circle-artifacts.com/0/ruby-rpm/ruby-2.5.2-1.el6.x86_64.rpm
   - CentOS 7: https://234-25909051-gh.circle-artifacts.com/0/ruby-rpm/ruby-2.5.2-1.el7.x86_64.rpm
- [x] Run Ruby 2.5.2

### CentOS 6

```
[mac]% docker pull centos:6
[mac]% docker run --rm -it centos:6 sh

# yum install -y libyaml
# rpm -i https://235-25909051-gh.circle-artifacts.com/0/ruby-rpm/ruby-2.5.2-1.el6.x86_64.rpm
# ruby -v -e 'puts File.read("/etc/centos-release")'
ruby 2.5.2p104 (2018-10-18 revision 65133) [x86_64-linux-gnu]
CentOS release 6.10 (Final)
```

### CentOS 7

```
[mac]% docker pull centos:7
[mac]% docker run --rm -it centos:7 sh

# yum install -y libyaml openssl
# rpm -ivh https://234-25909051-gh.circle-artifacts.com/0/ruby-rpm/ruby-2.5.2-1.el7.x86_64.rpm
# ruby -v -e 'puts File.read("/etc/centos-release")'
ruby 2.5.2p104 (2018-10-18 revision 65133) [x86_64-linux]
CentOS Linux release 7.5.1804 (Core)
```

### CODE REVIEW

**Comment by koshigoe** [comment]
https://bugs.ruby-lang.org/issues/14409
🙄

**Comment by koshigoe** [comment]
merged #62 

feedforce/ruby-rpm:centos6 includes Ruby

```
$ docker pull feedforce/ruby-rpm:centos6
centos6: Pulling from feedforce/ruby-rpm
9bfcefca2b8d: Already exists
aa1ac86e5058: Pull complete
9afbe3ae9994: Pull complete
79b0a1ff6c8c: Pull complete
d4f1a806b57c: Pull complete
9f4dfdab4c81: Pull complete
d74555e8222f: Pull complete
f2260e8dfcb2: Pull complete
Digest: sha256:b32db1ac26d762ae80a7aaf2d2d2dc6d926c168f09d3d4258a915fd91a454ef1
Status: Downloaded newer image for feedforce/ruby-rpm:centos6
$ docker run --rm feedforce/ruby-rpm:centos6 ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

**Comment by koshigoe** [comment]
rebase branch

**Comment by masutaka** [comment]
It seems the rpms were created without problems.

* https://circleci.com/gh/feedforce/ruby-rpm/235#artifacts/containers/0
* https://circleci.com/gh/feedforce/ruby-rpm/234#artifacts/containers/0

**Pull request merged**
