### PR TITLE
Ruby 3.1.0

### PR DESCRIPTION
**Pull request by jbalyozian**

### CODE REVIEW

**Review by tsub — COMMENTED** [review]
@jbalyozian Thank you for PR!
However, RPM builds fail on this branch.
This problem also occurs in existing PR #116 and is pending a fix in the Ruby.

* https://bugs.ruby-lang.org/issues/18373
* https://github.com/ruby/ruby/pull/5774
* https://github.com/ruby/ruby/commit/88cdd1a7460705bed5af6763378b47a12351aecf

<details>
<summary>Build result</summary>

```
$ docker build \
        -t feedforce/ruby-rpm:3.1-builder \
        -f Dockerfile-7 \
        --target builder \
        --cache-from=feedforce/ruby-rpm:centos7 \
        --build-arg RUBY_X_Y_VERSION=3.1 \
        --progress plain \
        .

...
#17 82.77 Generating RI format into /home/builder/rpmbuild/BUILD/ruby-3.1.0/.ext/rdoc...
#17 89.42 /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:95:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)
#17 89.42
#17 89.42     current directory: /home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension
#17 89.42 /home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/bin/ruby --disable\\=gems -I/home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/3.1.0/aarch64-linux -I /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib -r ./siteconf20221106-12970-fhddux.rb extconf.rb
#17 89.42 creating Makefile
#17 89.42
#17 89.42 current directory: /home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension
#17 89.42 make DESTDIR\\= clean
#17 89.42 make[1]: Entering directory `/home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension'
#17 89.42 make[1]: Leaving directory `/home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension'
#17 89.42
#17 89.42 current directory: /home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension
#17 89.42 make DESTDIR\\=
#17 89.42 make[1]: Entering directory `/home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension'
#17 89.42 make[1]: *** No rule to make target `/include/aarch64-linux/ruby/config.h', needed by `constants.o'.  Stop.
#17 89.42 make[1]: Leaving directory `/home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension'
#17 89.42
#17 89.42 make failed, exit code 2
#17 89.42
#17 89.42 Gem files will remain installed in /home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/gems/rbs-2.0.0 for inspection.
#17 89.42 Results logged to /home/builder/rpmbuild/BUILDROOT/ruby-3.1.0-1.el7.aarch64/usr/lib64/ruby/gems/3.1.0/extensions/aarch64-linux/3.1.0/rbs-2.0.0/gem_make.out
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:44:in `block in make'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:36:in `each'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:36:in `make'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/tempfile.rb:317:in `open'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/ext_conf_builder.rb:26:in `build'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:161:in `build_extension'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:195:in `block in build_extensions'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:192:in `each'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:192:in `build_extensions'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/installer.rb:847:in `build_extensions'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/installer.rb:318:in `install'
#17 89.42       from ./tool/rbinstall.rb:899:in `block in install'
#17 89.42       from ./tool/rbinstall.rb:713:in `no_write'
#17 89.42       from ./tool/rbinstall.rb:899:in `install'
#17 89.42       from ./tool/rbinstall.rb:1068:in `block (2 levels) in <main>'
#17 89.42       from ./tool/rbinstall.rb:1043:in `foreach'
#17 89.42       from ./tool/rbinstall.rb:1043:in `block in <main>'
#17 89.42       from ./tool/rbinstall.rb:1127:in `block in <main>'
#17 89.42       from ./tool/rbinstall.rb:1124:in `each'
#17 89.42       from ./tool/rbinstall.rb:1124:in `<main>'
#17 89.42 /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:95:in `run': make failed, exit code 2 (Gem::InstallError)
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:44:in `block in make'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:36:in `each'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:36:in `make'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/tempfile.rb:317:in `open'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/ext_conf_builder.rb:26:in `build'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:161:in `build_extension'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:195:in `block in build_extensions'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:192:in `each'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/ext/builder.rb:192:in `build_extensions'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/installer.rb:847:in `build_extensions'
#17 89.42       from /home/builder/rpmbuild/BUILD/ruby-3.1.0/lib/rubygems/installer.rb:318:in `install'
#17 89.42       from ./tool/rbinstall.rb:899:in `block in install'
#17 89.42       from ./tool/rbinstall.rb:713:in `no_write'
#17 89.42       from ./tool/rbinstall.rb:899:in `install'
#17 89.42       from ./tool/rbinstall.rb:1068:in `block (2 levels) in <main>'
#17 89.42       from ./tool/rbinstall.rb:1043:in `foreach'
#17 89.42       from ./tool/rbinstall.rb:1043:in `block in <main>'
#17 89.42       from ./tool/rbinstall.rb:1127:in `block in <main>'
#17 89.42       from ./tool/rbinstall.rb:1124:in `each'
#17 89.42       from ./tool/rbinstall.rb:1124:in `<main>'
#17 89.43 make: *** [do-install-all] Error 1
#17 89.43 error: Bad exit status from /var/tmp/rpm-tmp.0aQr45 (%install)
#17 89.43     bogus date in %changelog: Tue Dec 25 2015 Masato Tanaka <tanaka@feedforce.jp> - 2.3.0
#17 89.43     bogus date in %changelog: Tue Dec 17 2015 Masato Tanaka <tanaka@feedforce.jp> - 2.2.4
#17 89.43     bogus date in %changelog: Tue Aug 19 2015 Masato Tanaka <tanaka@feedforce.jp> - 2.2.3
#17 89.43     Bad exit status from /var/tmp/rpm-tmp.0aQr45 (%install)
#17 ERROR: executor failed running [/bin/sh -c /home/builder/ruby-rpm/scripts/build-rpm.sh $RUBY_X_Y_VERSION]: exit code: 1
------
 > [builder 8/8] RUN /home/builder/ruby-rpm/scripts/build-rpm.sh 3.1:
------
executor failed running [/bin/sh -c /home/builder/ruby-rpm/scripts/build-rpm.sh $RUBY_X_Y_VERSION]: exit code: 1
```

</details>

**Comment by jbalyozian** [comment]
Sorry about that; I didn't notice the existing PR when I submitted mine. Am I correct in stating that all Ruby `3.1.X` will fail to create an RPM? That is until a fix has been merged?

**Comment by tsub** [comment]
I have checked only Ruby 3.1.0 and 3.1.2. The same is probably true for 3.1.1 as well.
It could possibly be a different cause, but I do not know the detailed cause. We are not in a hurry to update to Ruby 3.1.0, so for now we are waiting to see what the Ruby community does.

**Comment by tsub** [comment]
@jbalyozian Sorry, this PR is closed as we have successfully built 3.1.3 on PR https://github.com/feedforce/ruby-rpm/pull/116.
Once again, thanks for creating this PR!

**Pull request closed without merging**
